/**
 * AI Disclosure rendering.
 *
 * Returns the disclosure HTML/text snippet for every published funnel.
 * Compliant with:
 *  - FTC AI Disclosure Guidance (Endorsement Guides Â§255)
 *  - EU AI Act Art. 50 (synthetic-content labeling)
 *  - ICMJE recommendation re AI authorship disclosure
 *
 * Behavior:
 *  - Free tier: REQUIRED, not removable.
 *  - Paid tiers: default-on, customer may toggle off only with admin
 *    permission. Outcome is logged via `ai_disclosure_rendered` event so
 *    we have a record of every page view that did or did not display it.
 *
 * The disclosure is also rendered on:
 *  - voice preamble (RevTry — see 07a Â§8.1, hard-coded TTS injection)
 *  - SMS first message
 *  - email footer
 *  - ad creative (where the ad platform permits a small disclosure line)
 */

export type PricingTier = "free" | "starter" | "growth" | "scale" | "agency";
export type Locale = "en-US" | "en-GB" | "es-ES" | "es-MX" | "pt-BR" | "fr-FR" | "de-DE";

export interface DisclosureOptions {
  tier: PricingTier;
  /** Operator name shown in the disclosure, e.g. workspace owner / business name. */
  operatorName: string;
  /** Customizable label override (paid tiers only). */
  customLabel?: string;
  /** Where it's being rendered — affects format. */
  surface: "page_footer" | "voice_preamble" | "sms_first_message" | "email_footer" | "ad_creative";
  /** Locale for the disclosure text. */
  locale?: Locale;
  /** Set to false to attempt to suppress — only honored on paid tiers. */
  visible?: boolean;
}

export interface DisclosureRendered {
  /** True if the disclosure was rendered (free tier never suppresses). */
  visible: boolean;
  /** Final text. */
  text: string;
  /** HTML representation (for page_footer / email_footer). */
  html: string;
  /** Hash of the canonical text (for audit). */
  textHash: string;
  /** Surface used. */
  surface: DisclosureOptions["surface"];
  /** Locale used. */
  locale: Locale;
}

const TEMPLATES: Record<Locale, { page: string; voice: string; sms: string; email: string; ad: string }> = {
  "en-US": {
    page: "Generated with GoFunnelAI — reviewed by {operator}.",
    voice:
      "Hi, this is {agent} calling on behalf of {operator}. This call is being recorded for quality and compliance. If you'd prefer not to be recorded, say 'opt out' now and I'll end the call.",
    sms: "Generated by AI on behalf of {operator}. Reply STOP to opt out.",
    email: "This message was generated with the help of AI on behalf of {operator}.",
    ad: "AI-generated, reviewed by {operator}.",
  },
  "en-GB": {
    page: "Generated with GoFunnelAI — reviewed by {operator}.",
    voice:
      "Hello, this is {agent} ringing on behalf of {operator}. This call is being recorded for quality and compliance. If you'd rather not be recorded, say 'opt out' now and I'll end the call.",
    sms: "Generated by AI on behalf of {operator}. Reply STOP to opt out.",
    email: "This message was generated with the help of AI on behalf of {operator}.",
    ad: "AI-generated, reviewed by {operator}.",
  },
  "es-ES": {
    page: "Generado con GoFunnelAI — revisado por {operator}.",
    voice:
      "Hola, soy {agent} llamando en nombre de {operator}. Esta llamada se graba por calidad y cumplimiento. Si prefiere no ser grabado, diga 'no acepto' ahora y terminarÃ© la llamada.",
    sms: "Generado por IA en nombre de {operator}. Responda STOP para darse de baja.",
    email: "Este mensaje fue generado con ayuda de IA en nombre de {operator}.",
    ad: "Generado por IA, revisado por {operator}.",
  },
  "es-MX": {
    page: "Generado con GoFunnelAI — revisado por {operator}.",
    voice:
      "Hola, soy {agent} llamando en nombre de {operator}. Esta llamada se graba para calidad y cumplimiento. Si prefiere no ser grabado, diga 'no acepto' ahora y terminarÃ© la llamada.",
    sms: "Generado por IA en nombre de {operator}. Responde STOP para darte de baja.",
    email: "Este mensaje fue generado con ayuda de IA en nombre de {operator}.",
    ad: "Generado por IA, revisado por {operator}.",
  },
  "pt-BR": {
    page: "Gerado com GoFunnelAI — revisado por {operator}.",
    voice:
      "OlÃ¡, aqui Ã© {agent} ligando em nome de {operator}. Esta chamada estÃ¡ sendo gravada por qualidade e conformidade. Se preferir nÃ£o ser gravado, diga 'nÃ£o aceito' agora e encerrarei a ligaÃ§Ã£o.",
    sms: "Gerado por IA em nome de {operator}. Responda STOP para sair.",
    email: "Esta mensagem foi gerada com ajuda de IA em nome de {operator}.",
    ad: "Gerado por IA, revisado por {operator}.",
  },
  "fr-FR": {
    page: "GÃ©nÃ©rÃ© avec GoFunnelAI — revu par {operator}.",
    voice:
      "Bonjour, c'est {agent} qui appelle au nom de {operator}. Cet appel est enregistrÃ© pour des raisons de qualitÃ© et de conformitÃ©. Si vous prÃ©fÃ©rez ne pas Ãªtre enregistrÃ©, dites 'refus' maintenant et je raccrocherai.",
    sms: "GÃ©nÃ©rÃ© par IA au nom de {operator}. RÃ©pondez STOP pour vous dÃ©sinscrire.",
    email: "Ce message a Ã©tÃ© gÃ©nÃ©rÃ© avec l'aide de l'IA au nom de {operator}.",
    ad: "GÃ©nÃ©rÃ© par IA, revu par {operator}.",
  },
  "de-DE": {
    page: "Erstellt mit GoFunnelAI — geprÃ¼ft von {operator}.",
    voice:
      "Hallo, hier ist {agent} im Auftrag von {operator}. Dieser Anruf wird zur QualitÃ¤ts- und Compliance-Sicherung aufgezeichnet. Wenn Sie nicht aufgezeichnet werden mÃ¶chten, sagen Sie jetzt 'Ablehnen' und ich beende den Anruf.",
    sms: "Von KI generiert im Auftrag von {operator}. Antworten Sie mit STOP zum Abmelden.",
    email: "Diese Nachricht wurde mit KI-UnterstÃ¼tzung im Auftrag von {operator} erstellt.",
    ad: "KI-generiert, geprÃ¼ft von {operator}.",
  },
};

function pickTemplate(locale: Locale, surface: DisclosureOptions["surface"]): string {
  const set = TEMPLATES[locale] ?? TEMPLATES["en-US"];
  switch (surface) {
    case "page_footer":
      return set.page;
    case "voice_preamble":
      return set.voice;
    case "sms_first_message":
      return set.sms;
    case "email_footer":
      return set.email;
    case "ad_creative":
      return set.ad;
  }
}

function interpolate(template: string, vars: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => vars[k] ?? `{${k}}`);
}

function sha256(input: string): string {
  // Tiny inline sha256 import — kept local so this file is browser-safe in
  // the Next.js render path if needed.
  // eslint-disable-next-line @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports
  const { createHash } = require("node:crypto") as typeof import("node:crypto");
  return createHash("sha256").update(input).digest("hex");
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] ?? c,
  );
}

export function renderDisclosure(opts: DisclosureOptions): DisclosureRendered {
  const locale = opts.locale ?? "en-US";
  const isFree = opts.tier === "free";
  const wantsVisible = opts.visible ?? true;
  // Free tier: ALWAYS visible. Paid tiers: customer may suppress with visible:false.
  const visible = isFree ? true : wantsVisible;

  const tpl = opts.customLabel && !isFree ? opts.customLabel : pickTemplate(locale, opts.surface);
  const text = interpolate(tpl, { operator: opts.operatorName, agent: "{agent}" });
  const html = `<div class="ai-disclosure" data-tier="${opts.tier}" data-surface="${opts.surface}">${escapeHtml(text)}</div>`;

  return {
    visible,
    text,
    html,
    textHash: sha256(text),
    surface: opts.surface,
    locale,
  };
}

/**
 * Resolve the operator string shown in the disclosure.
 * Falls back to "the operator" if no name provided.
 */
export function operatorName(input: { businessName?: string | null; userFullName?: string | null }): string {
  if (input.businessName && input.businessName.trim()) return input.businessName.trim();
  if (input.userFullName && input.userFullName.trim()) return input.userFullName.trim();
  return "the operator";
}
