#!/usr/bin/env bash
###############################################################################
# GoFunnelAI — Upstash Redis one-shot provisioning.
#
# Creates two databases (us-east-1 primary, eu-west-1 secondary), enables
# global replication, wires REST + native endpoints into Cloudflare Worker
# secrets, and writes the connection details back to .generated/redis.env.
#
# Required env:
#   UPSTASH_API_TOKEN     Personal API token (https://console.upstash.com/account/api)
#   UPSTASH_EMAIL         The email associated with the token
#   CLOUDFLARE_API_TOKEN
#   CLOUDFLARE_ACCOUNT_ID
###############################################################################

set -euo pipefail

UPSTASH_API="https://api.upstash.com/v2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

req() { command -v "$1" >/dev/null || { echo "missing: $1" >&2; exit 1; }; }
req curl
req jq

[[ -z "${UPSTASH_API_TOKEN:-}" ]] && { echo "UPSTASH_API_TOKEN not set" >&2; exit 1; }
[[ -z "${UPSTASH_EMAIL:-}" ]]    && { echo "UPSTASH_EMAIL not set"    >&2; exit 1; }

upstash() {
  curl -fsS -u "$UPSTASH_EMAIL:$UPSTASH_API_TOKEN" \
       -H "Content-Type: application/json" \
       "$@"
}

create_or_get() {
  local name="$1"
  local region="$2"
  local existing
  existing="$(upstash "$UPSTASH_API/redis/databases" | jq -r --arg n "$name" \
    '.[] | select(.database_name==$n) | .database_id' | head -n1)"
  if [[ -z "$existing" ]]; then
    upstash -X POST "$UPSTASH_API/redis/database" \
      -d "$(jq -nc --arg n "$name" --arg r "$region" \
        '{name:$n,region:$r,tls:true,eviction:true,primary_region:$r,read_regions:[]}')" \
      | jq -r '.database_id'
  else
    echo "$existing"
  fi
}

enable_global() {
  local id="$1"
  local read_regions="$2"
  upstash -X POST "$UPSTASH_API/redis/enable-multizone/$id" \
    -d "$(jq -nc --argjson regs "$read_regions" '{read_regions:$regs}')" \
    >/dev/null || true
}

echo ">> Provisioning Upstash Redis databases..."

us_id="$(create_or_get funnel-prod-us us-east-1)"
eu_id="$(create_or_get funnel-prod-eu eu-west-1)"
staging_id="$(create_or_get funnel-staging us-east-1)"
br_id="$(create_or_get funnel-prod-br sa-east-1)"

# Light-touch multi-region replication for production (us as primary, EU + BR
# as read regions). We pay only for the additional regions.
enable_global "$us_id" '["eu-west-1","sa-east-1"]'

fetch_details() {
  local id="$1"
  upstash "$UPSTASH_API/redis/database/$id"
}

us_json="$(fetch_details "$us_id")"
eu_json="$(fetch_details "$eu_id")"
staging_json="$(fetch_details "$staging_id")"
br_json="$(fetch_details "$br_id")"

extract() {
  local json="$1"
  local key="$2"
  echo "$json" | jq -r ".$key"
}

mkdir -p "$REPO_ROOT/infrastructure/.generated"
cat > "$REPO_ROOT/infrastructure/.generated/redis.env" <<EOF
# Generated by infrastructure/redis/setup.sh on $(date -u +%FT%TZ)

# --- production (us-east-1 primary) ---
UPSTASH_REDIS_REST_URL=$(extract "$us_json" rest_endpoint_url)
UPSTASH_REDIS_REST_TOKEN=$(extract "$us_json" rest_token)
UPSTASH_REDIS_URL=$(extract "$us_json" endpoint)
UPSTASH_REDIS_PORT=$(extract "$us_json" port)
UPSTASH_REDIS_PASSWORD=$(extract "$us_json" password)

# --- production (eu-west-1) ---
UPSTASH_REDIS_REST_URL_EU=$(extract "$eu_json" rest_endpoint_url)
UPSTASH_REDIS_REST_TOKEN_EU=$(extract "$eu_json" rest_token)

# --- production (sa-east-1) ---
UPSTASH_REDIS_REST_URL_BR=$(extract "$br_json" rest_endpoint_url)
UPSTASH_REDIS_REST_TOKEN_BR=$(extract "$br_json" rest_token)

# --- staging ---
UPSTASH_REDIS_REST_URL_STAGING=$(extract "$staging_json" rest_endpoint_url)
UPSTASH_REDIS_REST_TOKEN_STAGING=$(extract "$staging_json" rest_token)
UPSTASH_REDIS_URL_STAGING=$(extract "$staging_json" endpoint)
UPSTASH_REDIS_PASSWORD_STAGING=$(extract "$staging_json" password)
EOF

echo ">> Done. Outputs written to infrastructure/.generated/redis.env"
echo ">> Push these into Cloudflare Worker secrets via scripts/deploy.sh"
