import * as React from "react";
import type { BlockBaseProps } from "../types";

/**
 * footer.minimal — Logo + copyright + AI disclosure + slim link list.
 * Doc 18 B.9.1.
 */
export interface FooterMinimalContent {
  ai_disclosure_required: boolean;
  ai_disclosure_text_override?: string;
  links: Array<{ label: string; url: string }>;
  copyright_text?: string;
}

export interface FooterMinimalProps extends BlockBaseProps {
  content: FooterMinimalContent;
}

const DEFAULT_DISCLOSURE = "Parts of this page were generated by AI. Claims are reviewed by humans before publishing.";

export function FooterMinimal({ content, sectionId }: FooterMinimalProps): JSX.Element {
  return (
    <footer
      data-section-id={sectionId}
      data-section-type="footer.minimal"
      className="border-t border-slate-200 bg-white py-10"
    >
      <div className="mx-auto flex max-w-marketing flex-col gap-4 px-4 md:px-6">
        <div className="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center">
          <p className="text-caption text-slate-500">{content.copyright_text ?? `© ${new Date().getFullYear()} GoFunnelAI. All rights reserved.`}</p>
          {content.links.length > 0 && (
            <ul className="flex flex-wrap items-center gap-x-5 gap-y-2 text-caption">
              {content.links.map((l, i) => (
                <li key={i}>
                  <a href={l.url} className="text-slate-600 hover:text-signal-700 hover:underline">
                    {l.label}
                  </a>
                </li>
              ))}
            </ul>
          )}
        </div>
        {content.ai_disclosure_required && (
          <p className="border-t border-slate-100 pt-4 text-caption text-slate-500">
            {content.ai_disclosure_text_override ?? DEFAULT_DISCLOSURE}
          </p>
        )}
      </div>
    </footer>
  );
}
