import * as React from "react";
import type { BlockBaseProps } from "../types";

export interface FooterFullContent {
  company_name?: string;
  tagline?: string;
  columns: Array<{ title: string; links: Array<{ label: string; url: string }> }>;
  social?: Array<{ platform: string; url: string }>;
  ai_disclosure_required?: boolean;
  ai_disclosure_text_override?: string;
  copyright_text?: string;
}

export interface FooterFullProps extends BlockBaseProps {
  content: FooterFullContent;
}

const DEFAULT_DISCLOSURE = "Parts of this page were generated by AI. Claims are reviewed by humans before publishing.";

export function FooterFull({ content, sectionId }: FooterFullProps): JSX.Element {
  return (
    <footer
      data-section-id={sectionId}
      data-section-type="footer.full"
      className="border-t border-slate-200 bg-slate-50 py-14"
    >
      <div className="mx-auto max-w-marketing px-4 md:px-6">
        <div className="grid grid-cols-2 gap-8 md:grid-cols-5">
          <div className="col-span-2">
            <div className="text-h5 font-bold text-slate-900">{content.company_name ?? "GoFunnelAI"}</div>
            {content.tagline && <p className="mt-2 max-w-sm text-body-sm text-slate-600">{content.tagline}</p>}
            {content.social && (
              <ul className="mt-4 flex gap-3">
                {content.social.map((s, i) => (
                  <li key={i}>
                    <a href={s.url} className="text-caption font-medium text-slate-600 hover:text-signal-700 hover:underline" rel="noreferrer noopener" target="_blank">
                      {s.platform}
                    </a>
                  </li>
                ))}
              </ul>
            )}
          </div>
          {content.columns.map((col, i) => (
            <div key={i}>
              <h4 className="text-caption font-semibold uppercase tracking-wider text-slate-900">{col.title}</h4>
              <ul className="mt-4 space-y-2">
                {col.links.map((l, li) => (
                  <li key={li}>
                    <a href={l.url} className="text-body-sm text-slate-600 hover:text-signal-700 hover:underline">
                      {l.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <div className="mt-10 flex flex-col gap-3 border-t border-slate-200 pt-6 md:flex-row md:items-center md:justify-between">
          <p className="text-caption text-slate-500">{content.copyright_text ?? `© ${new Date().getFullYear()} GoFunnelAI. All rights reserved.`}</p>
          {content.ai_disclosure_required && (
            <p className="max-w-xl text-caption text-slate-500">
              {content.ai_disclosure_text_override ?? DEFAULT_DISCLOSURE}
            </p>
          )}
        </div>
      </div>
    </footer>
  );
}
