import Link from "next/link";
import { ArrowRight, Check, Minus } from "lucide-react";
import { HomeHero } from "@/components/marketing/HomeHero";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { INDUSTRY_HOOKS } from "@/lib/industries";

/**
 * Marketing home page.
 *
 * Every block of copy here is verbatim from doc 10 section 1.1.
 * Don't paraphrase. Edit copy@gofunnelai.com.
 */
export default function HomePage() {
  return (
    <>
      <HomeHero />

      {/* Social proof bar */}
      <section className="border-y border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800">
        <div className="container py-10">
          <div className="grid items-center gap-8 lg:grid-cols-[2fr_1fr]">
            <div>
              <p className="text-caption uppercase tracking-wider text-slate-500 mb-3">
                Trusted by operators in 30 industries - from solar to dental to SaaS.
              </p>
              <div className="flex flex-wrap items-center gap-6 grayscale opacity-70">
                {["Acme Solar", "Brightline Roofing", "PeakHVAC", "Northwind Dental", "OrbitSaaS"].map(
                  (logo) => (
                    <span key={logo} className="text-body-sm font-medium text-slate-600">
                      {logo}
                    </span>
                  ),
                )}
              </div>
            </div>
            <div className="lg:text-right">
              <div className="text-h2 font-display text-slate-900 dark:text-slate-50 tabular-nums">
                $14.2M
              </div>
              <p className="text-body-sm text-slate-500">
                in pipeline generated by GoFunnel users in the last 90 days.
              </p>
              <Link
                href="/methodology"
                className="text-caption text-signal-600 hover:underline underline-offset-2"
              >
                Measured by RevTry-qualified bookings x user-reported close rate. Methodology &rarr;
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="py-20 lg:py-28">
        <div className="container">
          <h2 className="text-h2 font-display text-center text-slate-900 dark:text-slate-50 max-w-3xl mx-auto">
            Three steps. Sixty seconds. One funnel that actually works.
          </h2>
          <div className="mt-14 grid gap-6 md:grid-cols-3">
            {[
              {
                n: "01",
                title: "Tell us your business.",
                body: "One sentence, a URL, a deck, or a 3-minute voice chat. Funnel pulls your brand voice, your offer, your audience, and what makes you different. You don't fill out a 40-field form.",
              },
              {
                n: "02",
                title: "Watch your funnel generate.",
                body: "Hero, form, offer, lead magnet PDF, email sequence, SMS sequence, voice script, and upsell flow - built in front of you in under a minute. Quality score below 80? Funnel rewrites it before you see it.",
              },
              {
                n: "03",
                title: "Launch ads + RevTry calls in 60 seconds.",
                body: "One click publishes to Meta, Google, TikTok, or LinkedIn. The moment a lead hits the form, RevTry calls them in your brand voice, qualifies them, and books them on your calendar. You wake up to bookings, not work.",
              },
            ].map((step) => (
              <Card key={step.n} className="border-slate-200">
                <CardContent className="p-8 space-y-3">
                  <div className="text-h5 font-mono text-signal-500 tabular-nums">{step.n}</div>
                  <h3 className="text-h4 text-slate-900 dark:text-slate-50">{step.title}</h3>
                  <p className="text-body text-slate-600 dark:text-slate-300">{step.body}</p>
                </CardContent>
              </Card>
            ))}
          </div>
          <div className="mt-10 text-center">
            <Link
              href="#industries"
              className="inline-flex items-center gap-1 text-body font-medium text-signal-600 hover:underline"
            >
              See it run on a real business <ArrowRight className="size-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* Industries grid */}
      <section id="industries" className="py-20 bg-slate-100/40 dark:bg-slate-800/40">
        <div className="container">
          <h2 className="text-h2 font-display text-slate-900 dark:text-slate-50 text-center">
            Pick your industry. See what we'd build you.
          </h2>
          <p className="mt-4 max-w-2xl mx-auto text-center text-body-lg text-slate-600 dark:text-slate-300">
            We've trained Funnel on the proven patterns from 30 industries - what hook converts a
            homeowner vs. what hook converts a CFO. Tap one to preview a sample funnel.
          </p>
          <div className="mt-12 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 lg:grid-cols-6 gap-3">
            {INDUSTRY_HOOKS.map((ind) => (
              <Link
                key={ind.slug}
                href={`/industries#${ind.slug}`}
                className="group flex flex-col gap-2 rounded-lg border border-slate-200 bg-white p-4 transition-all duration-small ease-out-brand hover:-translate-y-px hover:shadow-md hover:border-signal-300 dark:border-slate-700 dark:bg-slate-900"
              >
                <div className="aspect-video rounded bg-slate-100 dark:bg-slate-800 skeleton" />
                <div className="text-body-sm font-medium text-slate-900 dark:text-slate-50">
                  {ind.name}
                </div>
              </Link>
            ))}
          </div>
          <p className="mt-10 text-center text-body text-slate-600 dark:text-slate-300">
            Don't see yours? You're probably still covered.{" "}
            <Link href="/industries#tell-us" className="font-medium text-signal-600 hover:underline">
              Tell us what you sell &rarr;
            </Link>
          </p>
        </div>
      </section>

      {/* Founder note */}
      <section className="py-20 lg:py-28">
        <div className="container max-w-prose">
          <h2 className="text-h2 font-display text-slate-900 dark:text-slate-50">
            Why we built Funnel.
          </h2>
          <div className="mt-8 space-y-5 text-body-lg text-slate-700 dark:text-slate-200">
            <p>
              I spent eleven years building funnels by hand. Then four years paying agencies $8K a
              month to do it badly. Then two years using ClickFunnels, GoHighLevel, and seven other
              tools to stitch the work together myself.
            </p>
            <p>
              It always took weeks. The ads were always wrong. The leads were always cold. And
              nobody - not the agency, not the platform - was on the hook for whether it actually
              worked.
            </p>
            <p>
              GoFunnel is the version I wanted to exist. You type one sentence. It builds the page,
              writes the ads, calls the leads in your voice, and books the meetings. If the funnel
              doesn't earn you a dollar, you don't pay us a dollar.
            </p>
            <p>That last part isn't marketing. It's policy. The first $1,000 you make is yours alone.</p>
            <p className="text-body font-medium text-slate-500">- Ben & the team</p>
          </div>
        </div>
      </section>

      {/* Feature cards */}
      <section className="py-20 bg-slate-100/40 dark:bg-slate-800/40">
        <div className="container">
          <h2 className="text-h2 font-display text-slate-900 dark:text-slate-50 text-center">
            What's under the hood.
          </h2>
          <div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {[
              {
                title: "The Generation Engine",
                body: "Six specialized agents - Strategy, Copy, Design, Offer, Compliance, Quality - collaborate in parallel to build your funnel. Every output is judged before you see it. The Quality Bar is 80; we rewrite until we hit it.",
              },
              {
                title: "RevTry - your AI sales rep, on the phone in 6 seconds",
                body: "The moment a lead submits the form, RevTry calls them in a natural human voice. Qualifies, handles objections, books the call, sends the calendar invite. Powered by ElevenLabs. Costs about $0.18 a call.",
              },
              {
                title: "A CRM you'll actually open",
                body: "Every lead, every call, every transcript, every booking, every dollar - in one timeline. No Zapier duct tape. No 14-tab pipeline view that nobody updates. Just the thread of every relationship.",
              },
              {
                title: "One-click ad publishing",
                body: "Funnel writes the creative, picks the audience, sets the budget, and pushes to Meta, Google, TikTok, and LinkedIn from inside the app. New ad accounts get a sensible cap so you don't accidentally spend the rent.",
              },
              {
                title: "The 80-point quality bar",
                body: "Every funnel scores against 12 criteria - hook strength, form friction, trust signals, mobile fit, speed, compliance. Below 80, we silently rewrite. Above 80, you launch. You never ship a mediocre page on our watch.",
              },
              {
                title: "It gets better while you sleep",
                body: "Funnel watches what converts across every account (with privacy preserved), and rewrites the playbook nightly. The funnel you launch today is built on patterns we didn't know last week.",
              },
            ].map((f) => (
              <Card key={f.title} className="bg-white dark:bg-slate-900">
                <CardContent className="p-6 space-y-3">
                  <h3 className="text-h5 text-slate-900 dark:text-slate-50">{f.title}</h3>
                  <p className="text-body-sm text-slate-600 dark:text-slate-300">{f.body}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Comparison table */}
      <section className="py-20 lg:py-28">
        <div className="container">
          <div className="text-center">
            <h2 className="text-h2 font-display text-slate-900 dark:text-slate-50">
              Why not just use what you have?
            </h2>
            <p className="mt-3 text-body-lg text-slate-500">Fair question. Honest answers.</p>
          </div>
          <div className="mt-12 overflow-x-auto">
            <table className="w-full text-body-sm tabular-nums">
              <thead>
                <tr className="border-b border-slate-200 text-left">
                  <th className="py-3 pr-4 font-medium text-slate-500" />
                  <th className="py-3 px-4 font-semibold text-signal-700">Funnel</th>
                  <th className="py-3 px-4 font-medium text-slate-700">ClickFunnels</th>
                  <th className="py-3 px-4 font-medium text-slate-700">GoHighLevel</th>
                  <th className="py-3 px-4 font-medium text-slate-700">An agency</th>
                  <th className="py-3 pl-4 font-medium text-slate-700">DIY</th>
                </tr>
              </thead>
              <tbody className="text-slate-700 dark:text-slate-200">
                {COMPARISON_ROWS.map((row) => (
                  <tr key={row[0]} className="border-b border-slate-100">
                    <td className="py-3 pr-4 font-medium">{row[0]}</td>
                    <td className="py-3 px-4 font-semibold text-signal-700">{row[1]}</td>
                    <td className="py-3 px-4 text-slate-600">{row[2]}</td>
                    <td className="py-3 px-4 text-slate-600">{row[3]}</td>
                    <td className="py-3 px-4 text-slate-600">{row[4]}</td>
                    <td className="py-3 pl-4 text-slate-600">{row[5]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-8 max-w-3xl text-body text-slate-600 dark:text-slate-300">
            We're not better at everything. ClickFunnels has more visual customization. HighLevel
            has deeper agency tooling for managing 50+ sub-accounts. Agencies bring strategy that
            AI doesn't have yet. We're better at the thing 95% of operators actually need:{" "}
            <em>
              get a working funnel live this afternoon, get leads tomorrow, get bookings this week
            </em>
            . If that's not the job, one of these others might be the right call.
          </p>
        </div>
      </section>

      {/* Badge row */}
      <section className="py-16 border-y border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800">
        <div className="container text-center">
          <p className="text-caption uppercase tracking-wider text-slate-500 mb-6">
            Built on the best of what's available right now.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-4 opacity-70 grayscale">
            {["Anthropic", "Cloudflare", "PayPal", "Stripe", "ElevenLabs", "OpenAI"].map((b) => (
              <span key={b} className="text-body font-medium text-slate-600">
                {b}
              </span>
            ))}
          </div>
          <p className="mt-6 max-w-3xl mx-auto text-body-sm text-slate-500">
            We use Claude for reasoning, ElevenLabs for voice, Cloudflare for the edge, OpenAI for
            embeddings, and PayPal + Stripe for payments. We don't lock you into our stack - your
            data is portable, your domain is yours, your contacts export with one click.
          </p>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 lg:py-28">
        <div className="container">
          <h2 className="text-h2 font-display text-slate-900 dark:text-slate-50 text-center">
            What operators are saying.
          </h2>
          <div className="mt-12 grid gap-6 md:grid-cols-3">
            {TESTIMONIALS.map((t, i) => (
              <Card key={i} className="bg-white dark:bg-slate-900">
                <CardContent className="p-6 space-y-4">
                  <blockquote className="text-body italic text-slate-700 dark:text-slate-200">
                    "{t.quote}"
                  </blockquote>
                  <div className="flex items-center gap-3 pt-2 border-t border-slate-100">
                    <div className="size-10 rounded-full bg-slate-200" aria-hidden />
                    <div>
                      <div className="text-body-sm font-medium text-slate-900 dark:text-slate-50">
                        {t.name}
                      </div>
                      <div className="text-caption text-slate-500">{t.title}</div>
                    </div>
                  </div>
                  <Badge variant="signal">{t.metric}</Badge>
                </CardContent>
              </Card>
            ))}
          </div>
          <div className="mt-10 text-center">
            <Link
              href="/customers"
              className="text-body font-medium text-signal-600 hover:underline"
            >
              Read more stories &rarr;
            </Link>
          </div>
        </div>
      </section>

      {/* Pricing teaser */}
      <section className="py-20 bg-slate-100/40 dark:bg-slate-800/40">
        <div className="container max-w-prose text-center">
          <h2 className="text-h2 font-display text-slate-900 dark:text-slate-50">
            Pricing built for the smallest operator and the largest agency.
          </h2>
          <p className="mt-4 text-body-lg text-slate-600 dark:text-slate-300">
            Start free. Stay free until you earn your first $1,000. Then $49 a month. Scale to
            $997/month for the full agency white-label. PPP pricing for 90 countries. No setup
            fees, ever.
          </p>
          <Button size="lg" asChild className="mt-8">
            <Link href="/pricing">See full pricing &rarr;</Link>
          </Button>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-24 bg-signal-500">
        <div className="container max-w-prose text-center text-white">
          <h2 className="text-h2 font-display">Your competitor's funnel is older than yesterday.</h2>
          <p className="mt-4 text-body-lg text-signal-100">
            Yours could be live in a minute. Free until you make $1,000.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row sm:justify-center gap-4">
            <Button size="lg" variant="secondary" asChild className="bg-white text-signal-700 hover:bg-slate-50 border-white">
              <Link href="/signup">Build my funnel - free &rarr;</Link>
            </Button>
            <Link href="/grade" className="text-body text-signal-100 hover:text-white underline-offset-4 hover:underline self-center">
              Or audit your existing funnel first &rarr;
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 lg:py-28">
        <div className="container max-w-prose">
          <h2 className="text-h2 font-display text-slate-900 dark:text-slate-50 text-center">
            Questions, answered like a friend would.
          </h2>
          <Accordion type="single" collapsible className="mt-12">
            {FAQ.map((q, i) => (
              <AccordionItem key={i} value={`q${i}`}>
                <AccordionTrigger className="text-body font-medium text-slate-900 dark:text-slate-50 text-left">
                  {q.q}
                </AccordionTrigger>
                <AccordionContent className="text-body text-slate-700 dark:text-slate-300">
                  {q.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>
    </>
  );
}

const COMPARISON_ROWS: [string, string, string, string, string, string][] = [
  ["Time to first live funnel", "60 seconds", "4-12 hours", "8-20 hours", "2-6 weeks", "A weekend that becomes a month"],
  ["Writes the copy for you", "Yes - and rewrites until >=80/100", "No", "No", "Yes, eventually", "No"],
  ["Picks the offer + lead magnet", "Yes", "No", "No", "Sometimes", "No"],
  ["Calls + qualifies leads by voice", "Yes (RevTry)", "No", "Bolt-on add-on", "Human SDR - $4-8K/mo", "No"],
  ["Launches the ads", "Yes - Meta/Google/TikTok/LinkedIn", "No", "No", "Yes", "No"],
  ["Improves itself on your data", "Yes, nightly", "No", "No", "Sometimes", "No"],
  ["Floor price", "$0", "$97/mo", "$97/mo", "$4,000/mo", "\"Free\""],
  ["Setup fee", "$0", "$0", "$0", "$1,500-$10,000", "\"Free\""],
  ["Learning curve", "One sentence", "30+ hours", "60+ hours", "None - but you wait", "Steep"],
];

const TESTIMONIALS = [
  {
    quote: "I typed eight words at 9am. By lunch I had four booked calls. By Friday I'd closed two. I haven't opened ClickFunnels since.",
    name: "Jordan R.",
    title: "Owner, Coastal Solar",
    metric: "2 closed deals in week 1",
  },
  {
    quote: "RevTry called my lead in 6 seconds. The lead literally texted me afterward saying 'is that a real person?' That's when I knew this was different.",
    name: "Maya P.",
    title: "Director of Growth, North HVAC",
    metric: "84% booking rate",
  },
  {
    quote: "We replaced a $6K/month agency with GoFunnel and got better creative. The recursive learning thing is real - my Week 4 funnel destroys my Week 1 funnel.",
    name: "Sam K.",
    title: "Founder, OrbitSaaS",
    metric: "$72K annual savings",
  },
];

const FAQ = [
  { q: "Is the free tier really free, or is this a \"free trial\"?", a: "Really free. You can build one funnel, get up to 100 leads per month, and use 10 RevTry voice minutes per month - forever. We only charge when you outgrow it. And if you opt into \"Free until $1K,\" even your Starter plan is free until you've earned your first $1,000 from a Funnel-generated lead." },
  { q: "How many RevTry minutes do I get, and what counts as a minute?", a: "A minute is one minute of voice agent talk time on an outbound or inbound call. Free: 10/mo. Starter: 200/mo. Growth: 1,000/mo. Scale: 5,000/mo. Agency: 20,000/mo + pooled across sub-accounts. Overage is $0.18/minute, capped - we'll always ask before charging more." },
  { q: "Are ad spend dollars included in my plan?", a: "No. Ad spend goes directly from your card to Meta/Google/TikTok/LinkedIn - we're not in the middle. You see exactly what you spent on the platform. We charge $0 markup on ad spend, ever." },
  { q: "Can I use my own domain?", a: "Yes. Free + Starter get a yourname.gofunnelai.com subdomain. Growth and above get unlimited custom domains with auto-issued SSL. CNAME setup is a paste-one-record process; we verify it in real time." },
  { q: "Does Funnel work outside the US?", a: "Yes. We support 38 languages, 90 countries for PPP pricing, and RevTry voice is available in 28 voices across 12 languages. Local payment methods (iDEAL, SEPA, UPI, OXXO, and more) are live via Stripe. PayPal handles the rest." },
  { q: "Is it obvious that AI built my funnel? Do you disclose it?", a: "You can disclose it or not - your call. Our default policy: RevTry always identifies as an AI assistant when asked directly (\"Am I talking to a person?\" - \"I'm Funnel, an AI assistant calling on behalf of [your business]\"). The landing pages we build do not auto-disclose. Some regulated industries (legal, medical, financial) require disclosure; we handle that with a compliance pass at generation time." },
  { q: "Who owns the content GoFunnel generates for me?", a: "You do. Outright. Copy, designs, voice scripts, lead magnets - all yours, exportable, usable anywhere, even if you cancel. We claim no rights to your generated content. (See Terms section 7.)" },
  { q: "What's the refund policy?", a: "30-day money-back on any paid plan, no questions, no clawbacks on leads you already closed. Annual plans are pro-rated. RevTry overage is non-refundable once consumed (those are pass-through costs to ElevenLabs)." },
  { q: "Do you have an agency / white-label tier?", a: "Yes - the Agency plan at $997/month. Unlimited sub-accounts, your logo + domain, your branded login screen, your support email forwarding, your invoice. We sit invisibly behind your brand." },
  { q: "Can I customize RevTry's voice and personality?", a: "Yes. 28 voices out of the box, in 12 languages. You can clone a voice (yours or a paid VA's, with consent) on the Scale plan and up. You can also write custom system prompts that shape RevTry's tone - formal, playful, regional dialect, industry-specific vocabulary." },
  { q: "Is my data used to train your AI?", a: "No customer data is ever used to train foundation models. The \"recursive learning\" you hear about works on anonymized aggregate patterns - like \"in solar, hero headlines under 9 words convert 23% better.\" Your copy, leads, transcripts, and revenue are private to your account." },
  { q: "I'm in a regulated industry. Will this work for me?", a: "Yes, with a guardrail. Our Compliance agent runs on every generation in regulated verticals, checks for prohibited claims, and flags assets that need attorney review before launch. On publish you'll see a Publish Acknowledgment screen confirming you've reviewed the funnel for compliance with your local regs." },
];

// keep TS happy about unused icons in this file
void Check;
void Minus;
